Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria.Models
{
    public class Pizza
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(25)]
        public string Name { get; set; }


        [Column(TypeName="text")]
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(1000)]
        //[descriptionMinimumWords]
        public string Description { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(200)]
        public string Image { get; set; }
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        public double Price { get; set; }

        //FK

        public int? CategoryID { get; set; }
        public Category? Category { get; set; }

        public List<Ingredient>? Ingredients { get; set; }
        public Pizza()
        {
            System.Globalization.CultureInfo customCulture = (System.Globalization.CultureInfo)System.Threading.Thread.CurrentThread.CurrentCulture.Clone();
            customCulture.NumberFormat.NumberDecimalSeparator = ",";

            System.Threading.Thread.CurrentThread.CurrentCulture = customCulture;
        }
        public Pizza (string name, string description, string image, double price)
        {

            System.Globalization.CultureInfo customCulture = (System.Globalization.CultureInfo)System.Threading.Thread.CurrentThread.CurrentCulture.Clone();
            customCulture.NumberFormat.NumberDecimalSeparator = ",";

            System.Threading.Thread.CurrentThread.CurrentCulture = customCulture;


            Name = name;
            Description = description;
            Image = image;
            Price = price;
        }
    }
}

Models/PizzaForm.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace la_mia_pizzeria.Models
{
    public class PizzaForm
    {
        public Pizza Pizza { get; set; }
        public List<Category>? Categories { get; set; }
        public List<SelectListItem>? Ingredients { get; set; }
        public List<int>? SelectedIngredients { get; set; } 
    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria.Data;
using la_mia_pizzeria.Models;
using la_mia_pizzeria.Models.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.SqlServer.Server;
using Microsoft.CodeAnalysis;
using Azure;
using System.Diagnostics;


namespace la_mia_pizzeria.Controllers
{
    public class PizzaController : Controller
    {
        PizzaDbContext db;
        IPizzeriaRepository pizzeriaRepository;

        public PizzaController(IPizzeriaRepository _pizzeriaRepository) :base()
        {
            db = new PizzaDbContext();
            pizzeriaRepository = _pizzeriaRepository;   
        }
        public IActionResult Index()
        {

            List<Pizza> pizzaList = pizzeriaRepository.All();

            return View(pizzaList);
        }
        public IActionResult Details(int id)
        {
            Pizza singlePizza = pizzeriaRepository.GetById(id);
            return View(singlePizza);
        }
        public IActionResult Create()
        {
            PizzaForm formData = new PizzaForm();

            formData.Pizza = new Pizza();
            formData.Categories = db.Categories.ToList();
            formData.Ingredients = new List<SelectListItem>();

            List<Ingredient> ingredientsList = db.Ingredients.ToList();

            foreach (Ingredient ingredient in ingredientsList)
            {
                formData.Ingredients.Add(new SelectListItem(ingredient.Title, ingredient.Id.ToString()));
            }

            return View(formData);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PizzaForm formData)
        {
            
            if (!ModelState.IsValid)
            {
                formData.Categories = db.Categories.ToList();
                formData.Ingredients = new List<SelectListItem>();

                List<Ingredient> ingredientsList = db.Ingredients.ToList();

                foreach (Ingredient ingredient in ingredientsList)
                {
                    formData.Ingredients.Add(new SelectListItem(ingredient.Title, ingredient.Id.ToString()));
                }

                return View(formData);
            }

            //Aggiungo il sistema repository

            //formData.Pizza.Ingredients = new List<Ingredient>();

            //foreach (int ingredientId in formData.SelectedIngredients)
            //{
            //    Ingredient ingredient = db.Ingredients.Where(ingredient => ingredient.Id == ingredientId).FirstOrDefault();
            //    formData.Pizza.Ingredients.Add(ingredient);
            //}

            //db.Pizzas.Add(formData.Pizza);
            //db.SaveChanges();

            pizzeriaRepository.Create(formData.Pizza, formData.SelectedIngredients);

            return RedirectToAction("Index");
        }
        public IActionResult Update(int id)
        {
            Pizza pizzaToUpdate = pizzeriaRepository.GetById(id);

            if (pizzaToUpdate == null)
                return NotFound();
            PizzaForm formData = new PizzaForm();

            formData.Pizza = pizzaToUpdate;
            formData.Categories = db.Categories.ToList();
            formData.Ingredients = new List<SelectListItem>();

            List<Ingredient> ingredientsList = db.Ingredients.ToList();

            foreach (Ingredient ingredient in ingredientsList)
            {
                formData.Ingredients.Add(new SelectListItem(
                    ingredient.Title,
                    ingredient.Id.ToString(),
                    pizzaToUpdate.Ingredients.Any(i => i.Id == ingredient.Id)
                   ));
            }

            return View(formData);
        }
        [HttpPost]
        public IActionResult Update(int id, PizzaForm formData)
        {

            if (!ModelState.IsValid)
            {
                formData.Pizza.Id = id;
                formData.Categories = db.Categories.ToList();
                formData.Ingredients = new List<SelectListItem>();

                List<Ingredient> ingredientsList = db.Ingredients.ToList();

                foreach (Ingredient ingredient in ingredientsList)
                {
                    formData.Ingredients.Add(new SelectListItem(ingredient.Title, ingredient.Id.ToString()));
                }

                return View(formData);
            }


            Pizza pizzaToUpdate = pizzeriaRepository.GetById(id);   

            if (pizzaToUpdate == null)
            {
                return NotFound();
            }

            //Aggiungo il nuovo sistema repository

            //pizzaToUpdate.Name = formData.Pizza.Name;
            //pizzaToUpdate.Description = formData.Pizza.Description;
            //pizzaToUpdate.Image = formData.Pizza.Image;
            //pizzaToUpdate.CategoryID = formData.Pizza.CategoryID;

            //pizzaToUpdate.Ingredients.Clear();

            //if (formData.SelectedIngredients == null)
            //{
            //    formData.SelectedIngredients = new List<int>();
            //}

            //foreach (int ingredientId in formData.SelectedIngredients)
            //{
            //    Ingredient ingredient = db.Ingredients.Where(i => i.Id == ingredientId).FirstOrDefault();
            //    pizzaToUpdate.Ingredients.Add(ingredient);
            //}

            //db.SaveChanges();

            pizzeriaRepository.Update(pizzaToUpdate, formData.Pizza, formData.SelectedIngredients);

            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Pizza pizzaToDelete = pizzeriaRepository.GetById(id);

            if (pizzaToDelete == null)
            {
                return NotFound();
            }

            pizzeriaRepository.Delete(pizzaToDelete);


            return RedirectToAction("Index");
        }
    }
}

Views/Pizza/Create.cshtml
@model PizzaForm

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Aggiungi nuova pizza</h1>
            </div>
            <form asp-controller="Pizza" asp-action="Create" method="post">

                <div class="mb-3">
                    <strong>Immagine:</strong>
                    <input asp-for="Pizza.Image" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Image" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Nome:</strong>
                    <input asp-for="Pizza.Name" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Prezzo:</strong>
                    <input asp-for="Pizza.Price" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Price" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Contenuto:</strong>
                    <textarea asp-for="Pizza.Description" rows="10" class="d-block w-100"></textarea>
                    <span asp-validation-for="Pizza.Description" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Categoria:</strong>
                    <select asp-for="Pizza.CategoryID" rows="10" class="d-block w-100">

                        @foreach (Category category in Model.Categories)
                        {
                            @if (Model.Pizza.CategoryID == category.Id)
                            {
                                <option value="@category.Id" selected>@category.Name</option>
                            }
                            else
                            {
                                <option value="@category.Id">@category.Name</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="Pizza.CategoryID" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Ingredienti:</strong>
                    <select asp-for="SelectedIngredients"
                            asp-items="@Model.Ingredients"
                            multiple="multiple"
                            size="10"
                            class="form-control mb-2 mr-sm-2 ml-sm-3 leftList">
                    </select>
                </div>
                <div class="text-end">
                    <input type="submit" class="btn btn-small btn-success" value="Salva">
                </div>

            </form>
        </div>
    </div>
</div>

Views/Pizza/Details.cshtml
@model Pizza

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Dettagli post</h1>
            </div>
            <div class="post-single-image-container">
                <img src="@Model.Image">
            </div>
            <p>
                <strong>Nome:</strong>
                @Model.Name
            </p>
            <p>
                <strong>Contenuto:</strong>
                @Model.Description
            </p>
            <p>
                <strong>Prezzo:</strong>
                @Model.Price &euro;
            </p>
            <p>
                <strong>Categoria:</strong>
                @Model.Category.Name
            </p>
            <p>
                <strong>Ingredienti:</strong>
                @foreach (Ingredient ingredient in Model.Ingredients)
                {
                    <div>
                        <span class="badge bg-primary">@ingredient.Title</span>
                    </div>
                }
            </p>
        </div>
    </div>
</div>

Views/Pizza/Index.cshtml
<h1>Ecco l'elenco delle nostre pizze</h1>

@model List<Pizza>
@if(Model.Count() == 0){
    <h3 class="text-center">Menù non ancora disponibile</h3>
}else{
<div>
        <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Foto</th>
                <th scope="col">Categoria</th>
                <th scope="col">Operazioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach(Pizza pizza in Model){
                <tr>
                    <th scope="row"><a>@pizza.Id</a></th>
                    <td>@pizza.Name</td>
                    <td><img src="@pizza.Image" alt="@pizza.Name"/></td>
                    <td>@pizza.Category.Name</td>
                        <td class="d-flex">
                            <a href="@Url.Action("Details",new {id = pizza.Id})" role="button" class="btn btn-primary">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-zoom-in" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
                                    <path d="M10.344 11.742c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1 6.538 6.538 0 0 1-1.398 1.4z" />
                                    <path fill-rule="evenodd" d="M6.5 3a.5.5 0 0 1 .5.5V6h2.5a.5.5 0 0 1 0 1H7v2.5a.5.5 0 0 1-1 0V7H3.5a.5.5 0 0 1 0-1H6V3.5a.5.5 0 0 1 .5-.5z" />
                                </svg>
                            </a>
                            <a href="@Url.Action("Update",new {id = pizza.Id})" role="button" class="btn btn-warning">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                                </svg>
                            </a>
                            <form asp-controller="Pizza" asp-action="Delete" asp-route-id="@pizza.Id" method="post">
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z" />
                                    </svg>
                                </button>
                            </form>
                        </td>
                </tr>
            }
        </tbody>
    </table>
</div>
}

Views/Pizza/Update.cshtml
@model PizzaForm

<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="d-flex align-items-center">
                <h1 class="mt-3 mb-3">Modifica dettagli pizza</h1>
            </div>
            <form asp-controller="Pizza" asp-action="Update" asp-route-id="@Model.Pizza.Id" method="post">

                <div class="mb-3">
                    <strong>Immagine:</strong>
                    <input asp-for="Pizza.Image" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Image" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Nome:</strong>
                    <input asp-for="Pizza.Name" class="d-block w-100" />
                    <span asp-validation-for="Pizza.Name" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Prezzo:</strong>
                    <input asp-for="Pizza.Price" class="d-block w-100"/>
                    <span asp-validation-for="Pizza.Price" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Contenuto:</strong>
                    <textarea asp-for="Pizza.Description" rows="10" class="d-block w-100"></textarea>
                    <span asp-validation-for="Pizza.Description" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Categoria:</strong>
                    <select asp-for="Pizza.CategoryID" rows="10" class="d-block w-100">

                        @foreach (Category category in Model.Categories)
                        {
                            @if (Model.Pizza.CategoryID == category.Id)
                            {
                                <option value="@category.Id" selected>@category.Name</option>
                            }
                            else
                            {
                                <option value="@category.Id">@category.Name</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="Pizza.CategoryID" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <strong>Ingredienti:</strong>
                    <select asp-for="SelectedIngredients"
                            asp-items="@Model.Ingredients"
                            multiple="multiple"
                            size="10"
                            class="form-control mb-2 mr-sm-2 ml-sm-3 leftList">
                    </select>
                </div>
                <div class="text-end">
                    <input type="submit" class="btn btn-small btn-success" value="Salva">
                </div>


            </form>
        </div>
    </div>
</div>